format_version: 10
pipelines:
  terraform-destroy1:
    group: expense-terraform
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-2ae7d73:
        git: https://github.com/pdevops/terraform-module.git
        shallow_clone: false
        auto_update: true
        branch: main
    secure_variables:
    stages:
      - DEV:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: false
          approval:
            type: manual
            allow_only_on_success: false
          jobs:
            test-job:
              timeout: 0
              tasks:
                - exec: { command: terraform, arguments: ["init","-backend-config=dev-state/state.tfvars"], run_if: passed }
                - exec: { command: terraform, arguments: ["destroy","-var-file=dev-state/main.tfvars","-auto-approve"], run_if: passed }